// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUs-oUODCe9syD8PTZUhFbjhbLqShxJ-M',
    appId: '1:1033008770432:android:199d5a2cf6936bdad4e565',
    messagingSenderId: '1033008770432',
    projectId: 'event-plannig-app',
    storageBucket: 'event-plannig-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOiFspIgg0_j6GOV8GL15L-a78zAD_2Y',
    appId: '1:1033008770432:ios:d066dba3da40a173d4e565',
    messagingSenderId: '1033008770432',
    projectId: 'event-plannig-app',
    storageBucket: 'event-plannig-app.firebasestorage.app',
    androidClientId:
        '1033008770432-ov4lm43hsh84jpi7f2rin6qbscc4d5jr.apps.googleusercontent.com',
    iosClientId:
        '1033008770432-812qbdf64i6q0ef8m3h1fphuosb0jr4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn2F65RhjkuQZvXA7RUCk5rUI6361LVWk',
    appId: '1:1033008770432:web:f7ec1cf1de7e9f58d4e565',
    messagingSenderId: '1033008770432',
    projectId: 'event-plannig-app',
    authDomain: 'event-plannig-app.firebaseapp.com',
    storageBucket: 'event-plannig-app.firebasestorage.app',
    measurementId: 'G-QB93R2DCWR',
  );
}
